### ISSUE TITLE
Customers wet themselves and still enter bathroom line or wet themselves en-route to the bathroom line.

### ISSUE THREAD

**Issue by ALewdBoi** [ZorbZorbZorb/Project_2#31]
Recommend perhaps customers "stick a cork in it" for a 20-second window on starting check to go to the bathroom to prevent customers from becoming immediately stuck in the entry queue. Losing control of those spots should be a failure of the player and not an uncontrollable thing.

Issue was previously marked resolved but is recurring in new release.

**Comment by ZorbZorbZorb** [comment]
Can no longer replicate.
