### ISSUE TITLE
Rare "High Capacity" Customer

### ISSUE THREAD

**Issue by ALewdBoi** [ZorbZorbZorb/Project_2#79]
Perhaps we could have a rare customer spawn with extremely high bladder capacity, ~2L or so instead of the soft cap of around 1.5L currently in game.

We could have it knowable through visual bulge or some other cue so the player can know this customer can be put off to the side and made to wait _much_ longer before relief is necessary and lets the player strategize around when to try to relieve them as it will take a long time for them to drain.

Perhaps as well these customers should be much more capable of pinching it off with their large capacity, so players can confidently make them stop or send them away with a litre or more still in them.

**Comment by ZorbZorbZorb** [comment]
> Perhaps we could have a rare customer spawn with extremely high bladder capacity, ~2L or so instead of the soft cap of around 1.5L currently in game.

Completed in #97 https://github.com/ZorbZorbZorb/Project_2/blob/545f8a3356e99b658729f41fb60728c3b5ae9e74/Assets/Scripts/Customers/BladderSize.cs#L1-L6

> We could have it knowable through visual bulge or some other cue so the player can know this customer can be put off to the side and made to wait much longer before relief is necessary and lets the player strategize around when to try to relieve them as it will take a long time for them to drain.

Needs discussion around how art will work out with @DWRolo but I'm all for it

> Perhaps as well these customers should be much more capable of pinching it off with their large capacity, so players can confidently make them stop or send them away with a litre or more still in them.

Completed in 68f183137c08b07642f4044e877302a72dfe0d25
